# Wallace colours for fzf (https://github.com/junegunn/fzf)
# Generated by generate.py - do not edit by hand.
# Source this file from your shell profile, then pick one:
#   export FZF_DEFAULT_OPTS="$FZF_DEFAULT_OPTS $WALLACE_FZF_AA"
#   export FZF_DEFAULT_OPTS="$FZF_DEFAULT_OPTS $WALLACE_FZF_AAA"

WALLACE_FZF_AA="--color=bg:#002909,fg:#61a972,bg+:#004211,fg+:#98e2a7,hl:#c8854c,hl+:#e5a067,query:#7cc58c,info:#969696,prompt:#30ac99,pointer:#98e2a7,marker:#b1933d,spinner:#969696,header:#969696,border:#2b7440,label:#969696,gutter:#001300,separator:#2b7440,scrollbar:#2b7440"
WALLACE_FZF_AAA="--color=bg:#002909,fg:#7cc58c,bg+:#004211,fg+:#98e2a7,hl:#e5a067,hl+:#ffbc82,query:#98e2a7,info:#b1b1b1,prompt:#53c8b4,pointer:#98e2a7,marker:#ccae5a,spinner:#b1b1b1,header:#b1b1b1,border:#2b7440,label:#b1b1b1,gutter:#001300,separator:#2b7440,scrollbar:#2b7440"
